# Generated by Django 2.2 on 2021-07-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atm',
            name='cardno',
            field=models.CharField(max_length=16),
        ),
    ]
