# Generated by Django 2.2 on 2021-07-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_auto_20210705_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atm',
            name='pin',
            field=models.CharField(max_length=4),
        ),
    ]
